### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by Zumbalamambo** [mahehu/TUT-live-age-estimator#1]
Is there any tensorflow implementation of the code ?

**Comment by mahehu** [comment]
We are training TF versions now. Should be ready to commit in a few weeks.

**Comment by Zumbalamambo** [comment]
can you please share the dataset for age?

**Comment by mahehu** [comment]
We use these sets

https://data.vision.ee.ethz.ch/cvl/rrothe/imdb-wiki/

http://gesture.chalearn.org/2016-looking-at-people-cvpr-challenge

**Comment by Zumbalamambo** [comment]
are you using imdb celebrity faces? because the cropped face which of 7 gb is not proper. the age of people is not exact. I will share with you the code that I used to segregate the images into various folders based on their age. after segregation, I noticed that even the teenagers are in old people age folder. However imdb wiki dataset it good enough..

```
import numpy as np
from utils import get_meta
import cv2
import os
from shutil import copy
db = "imdb"
mat_path = "data/{}_crop/{}.mat".format(db, db)
print (mat_path)
full_path, dob, gender, photo_taken, face_score, second_face_score, age\
    = get_meta(mat_path, db)

print("#images: {}".format(len(face_score)))
print("#images with inf scores: {}".format(np.isinf(face_score).sum()))

img_paths = []
photo_root = "data/{}_crop/".format(db)


for i in range(len(age)):
    if age[i] == 7:
        print (photo_root +str (full_path[i][0]))
        img_cv = cv2.imread(os.path.join(photo_root, full_path[i][0]))

        copy(photo_root + "/" + str(full_path[i][0]), "seven")
```

**Comment by Zumbalamambo** [comment]
@mahehu any ideas as of how I can get this done?

**Comment by elmoutaouakkil** [comment]
Can you please share with us more details (files to compile ...) ?

**Comment by mahehu** [comment]
I think all these issues are addressed in the current version.
