### ISSUE TITLE
xrandr | grep "\*" | cut -d" " -f4 do not work on windows

### ISSUE THREAD

**Issue by Vaunorage** [mahehu/TUT-live-age-estimator#3]
Is this only supposed to work on linux because I think its a linux command...

xrandr | grep "\*" | cut -d" " -f4

I get this error : 

Using TensorFlow backend.
'xrandr' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:/Users/vaun_/PycharmProjects/TUT-live-age-estimator/EstimateAge.py", line 23, in <module>
    controllerThread = ControllerThread.ControllerThread(params)
  File "C:\Users\vaun_\PycharmProjects\TUT-live-age-estimator\ControllerThread.py", line 45, in __init__
    self.resolution = [int(s) for s in self.resolution]
  File "C:\Users\vaun_\PycharmProjects\TUT-live-age-estimator\ControllerThread.py", line 45, in <listcomp>
    self.resolution = [int(s) for s in self.resolution]
ValueError: invalid literal for int() with base 10: ''

Thanks

**Comment by AkkiLingwal96** [comment]
I'm facing the same issue.. did you find any solution?

**Comment by 1vash** [comment]
Use `'echo 1920x1080'` (your display resolution, that's mine) instead of `xrandr | grep "\*" | cut -d"` :) Easy fix

**Comment by mahehu** [comment]
Thanks @innjoshka 

This is indeed the solution, and the line is there only to figure out the display resolution automatically.
