### ISSUE TITLE
What does this code mean

### ISSUE THREAD

**Issue by 2p990i9hpral** [mahehu/TUT-live-age-estimator#4]
i don't understand why below code is used

I expect two lines to be Convert range of x from 0 to 1, 
but the subtraction codes below are totally incomprehensible.

i want to know why these code is used
thank you
```
@staticmethod
def preprocess_input(img):
	x = img - img.min()
	x = 255.0 * x / x.max()

	x[..., 0] -= 103.939
	x[..., 1] -= 116.779
	x[..., 2] -= 123.68
	return x
```

**Comment by mahehu** [comment]
The subtraction originates from the mean color values of the imagenet dataset. The same procedure is used also in [keras.applications](https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py#L64), whose pretrained models we use as the starting point of our training process.

We are preparing a new pull of a set of faster and more accurate models. In the next version (in the next few weeks), we are dropping this subtraction to simplify the code.

**Comment by 2p990i9hpral** [comment]
> The subtraction originates from the mean color values of the imagenet dataset. The same procedure is used also in [keras.applications](https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py#L64), whose pretrained models we use as the starting point of our training process.
> 
> We are preparing a new pull of a set of faster and more accurate models. In the next version (in the next few weeks), we are dropping this subtraction to simplify the code.

It is very good news.
I'm looking forward to the next release.
Please do your best!
