### ISSUE TITLE
add windows dependency please..

### ISSUE THREAD

**Issue by 2p990i9hpral** [mahehu/TUT-live-age-estimator#6]
I only use Windows.
legacy project was successfully run with Windows.
but current updated project is doesn't work with Windows because "faiss" module is not support Windows.
can you modify this problem?
i really want Windows version.
thank you!

**Comment by jtomm** [comment]
Hey,

Thanks for raising the issue, I did not realize faiss doesn't work on Windows. If you want, you can try [the Windows port](https://github.com/bitsun/faiss-windows), but I have not tried it and it might not work. I have prepared a branch with faiss (and celebrity features unfortunately) removed [here](https://github.com/jtomm/TUT-live-age-estimator/tree/no-celeb), which hopefully works on Windows. 
 
We may try to also make faiss optional on this branch if we have time, but no guarantees.

**Comment by 2p990i9hpral** [comment]
> Hey,
> 
> Thanks for raising the issue, I did not realize faiss doesn't work on Windows. If you want, you can try [the Windows port](https://github.com/bitsun/faiss-windows), but I have not tried it and it might not work. I have prepared a branch with faiss (and celebrity features unfortunately) removed [here](https://github.com/jtomm/TUT-live-age-estimator/tree/no-celeb), which hopefully works on Windows.
> 
> We may try to also make faiss optional on this branch if we have time, but no guarantees.

thank you :)
