### ISSUE TITLE
Camera Support

### ISSUE THREAD

**Issue by c0nfus3d** [mahehu/TUT-live-age-estimator#7]
Are only USB cameras supported?

I have a network camera with RTSP enabled. Can this be a valid video source?

Thanks.

**Comment by ForgetMe17** [comment]
Faiss-cpu is not supported on WIN10
How can i use this on WIN10?

**Comment by mahehu** [comment]
We use OpenCV's `VideoCapture` interface for grabbing. Currently, the code assumes USB camera, but `VideoCapture` can be configured for RTSP as well.

See for example [this SO thread](https://stackoverflow.com/questions/40875846/capturing-rtsp-camera-using-opencv-python), and modify the `VideoCapture` initialization in the code accordingly.
