### ISSUE TITLE
Save Resultant Video Option

### ISSUE THREAD

**Issue by Israrulhaq190** [mahehu/TUT-live-age-estimator#9]
Hi,
  Thank you for awesome implementation. I was wondering how can we save the resultant video ? which files should i modify for this ?

**Comment by mahehu** [comment]
Thank you for your kind words.

The display is refreshed starting on line 300 of `ControllerThread.py`. You can try saving the most recent frame (in numpy array `frame`) after these lines:
```
        cv2.imshow(self.caption, frame)
        key = cv2.waitKey(10)
        
        if key == 27:
             self.terminate()
```
Either save individual frames as jpeg's and pull them together by `ffmpeg`; or initialize a opencv `VideoCapture` object and save directly to a video file.

Alternatively, just record the screen using a screen capture software. I've used VokoScreen to create some demo videos of this.
